### ISSUE TITLE
新版青龙改变了目录结构

### ISSUE THREAD

**Issue by Cyiming** [Ukenn2112/qinglong_Backup#2]
应该小更新下了

**Comment by Ukenn2112** [comment]
嗯~ o(*￣▽￣*)o 现已适配

**Comment by Cyiming** [comment]
> 嗯~ o(_￣▽￣_)o 现已适配

好快

 能麻烦问下我依赖安装不上 我又不会看报错 

 好像不是网络问题 试了下其他模块能安装 我本地电脑也能安装

按照报错安装Pillow也报错

好像核心是**This is an issue with the package mentioned above, not pip.** 但是青龙又不能指定安装方式

Looking in indexes: https://pypi.mirrors.ustc.edu.cn/simple/
Collecting aligo
  Using cached https://mirrors.bfsu.edu.cn/pypi/web/packages/fe/d4/eb35b418ac8a968602b4c4277c1ff6f9a93c78d748e999e51888d6872629/aligo-3.3.1-py3-none-any.whl (113 kB)
Collecting coloredlogs
  Using cached https://mirrors.bfsu.edu.cn/pypi/web/packages/a7/06/3d6badcf13db419e25b07041d9c7b4a2c331d3f4e7134445ec5df57714cd/coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
Requirement already satisfied: tqdm>=4.50.0 in /usr/lib/python3.9/site-packages (from aligo) (4.63.1)
Requirement already satisfied: qrcode[pil] in /usr/lib/python3.9/site-packages (from aligo) (7.3.1)
Collecting qrcode-terminal
  Using cached https://mirrors.bfsu.edu.cn/pypi/web/packages/96/62/2422c088b7219db9f78c912418254db9896d1b20ab15e83aae2821419a65/qrcode-terminal-0.8.tar.gz (1.7 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting arrow
  Using cached https://mirrors.bfsu.edu.cn/pypi/web/packages/36/e7/3043959c8e3e3d6e346b69417e85daa591f9c018b99c383cc3f316bbf269/arrow-1.2.2-py3-none-any.whl (64 kB)
Requirement already satisfied: python-dateutil>=2.7.0 in /usr/lib/python3.9/site-packages (from arrow->aligo) (2.8.2)
Collecting humanfriendly>=9.1
  Using cached https://mirrors.bfsu.edu.cn/pypi/web/packages/f0/0f/310fb31e39e2d734ccaa2c0fb981ee41f7bd5056ce9bc29b2248bd569169/humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
Collecting Pillow
  Using cached https://mirrors.bfsu.edu.cn/pypi/web/packages/03/a3/f61a9a7ff7969cdef2a6e0383a346eb327495d20d25a2de5a088dbb543a6/Pillow-9.0.1.tar.gz (49.5 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Using legacy 'setup.py install' for qrcode-terminal, since package 'wheel' is not installed.
Using legacy 'setup.py install' for Pillow, since package 'wheel' is not installed.
  Running setup.py install for Pillow: started
  Running setup.py install for Pillow: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Running setup.py install for Pillow did not run successfully.
  │ exit code: 1
  ╰─> [176 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.9
      creating build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/_tkinter_finder.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/WebPImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/IptcImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/FliImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/ExifTags.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/DcxImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/SunImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/WalImageFile.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/SgiImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/TgaImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/IcoImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/ImageMode.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/ImagePath.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/EpsImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/GimpGradientFile.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/TiffImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/_version.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/__init__.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/ImageGrab.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/PixarImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/FtexImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/ImageFilter.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/ImageChops.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/ImageOps.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/JpegImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/PsdImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/TarIO.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/ImageQt.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/BlpImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/WmfImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/ImageMath.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/_util.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/ImageShow.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/ImageWin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/GdImageFile.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/ImageCms.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/MpoImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/PalmImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/ImageTk.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/Image.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/GifImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/ImageColor.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/PngImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/TiffTags.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/ImageFont.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/PcxImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/GimpPaletteFile.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/ImageStat.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/FontFile.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/PdfImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/MpegImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/ImImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/PcfFontFile.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/ImageDraw2.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/ImtImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/MicImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/PSDraw.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/CurImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/PaletteFile.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/ImageDraw.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/ImageEnhance.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/BmpImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/_binary.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/PyAccess.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/XbmImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/features.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/MspImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/JpegPresets.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/ContainerIO.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/PcdImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/PpmImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/DdsImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/ImageFile.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/ImageTransform.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/ImageSequence.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/PdfParser.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/FpxImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/ImagePalette.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/__main__.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/GbrImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/BdfFontFile.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/ImageMorph.py -> build/lib.linux-x86_64-3.9/PIL
      copying src/PIL/XpmImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
      running egg_info
      writing src/Pillow.egg-info/PKG-INFO
      writing dependency_links to src/Pillow.egg-info/dependency_links.txt
      writing top-level names to src/Pillow.egg-info/top_level.txt
      reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.c'
      warning: no files found matching '*.h'
      warning: no files found matching '*.sh'
      warning: no previously-included files found matching '.appveyor.yml'
      warning: no previously-included files found matching '.clang-format'
      warning: no previously-included files found matching '.coveragerc'
      warning: no previously-included files found matching '.editorconfig'
      warning: no previously-included files found matching '.readthedocs.yml'
      warning: no previously-included files found matching 'codecov.yml'
      warning: no previously-included files matching '.git*' found anywhere in distribution
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      no previously-included directories found matching '.ci'
      writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
      running build_ext
      
      
      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.
      
      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html
      
      Traceback (most recent call last):
        File "/tmp/pip-install-r3kfuua6/pillow_5eb2600248a44f17a4e4b03bec0a429e/setup.py", line 989, in <module>
          setup(
        File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.9/site-packages/setuptools/command/install.py", line 61, in run
          return orig.install.run(self)
        File "/usr/lib/python3.9/distutils/command/install.py", line 546, in run
          self.run_command('build')
        File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.9/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/usr/lib/python3.9/distutils/command/build_ext.py", line 340, in run
          self.build_extensions()
        File "/tmp/pip-install-r3kfuua6/pillow_5eb2600248a44f17a4e4b03bec0a429e/setup.py", line 804, in build_extensions
          raise RequiredDependencyException(f)
      __main__.RequiredDependencyException: zlib
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-r3kfuua6/pillow_5eb2600248a44f17a4e4b03bec0a429e/setup.py", line 1009, in <module>
          raise RequiredDependencyException(msg)
      __main__.RequiredDependencyException:
      
      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.
      
      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> Pillow

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by Ukenn2112** [comment]
你尝试下先在容器内执行这段代码看看，估计 Docker 里没有 Pillow 安装所需要的环境

```ssh
apk add zlib libjpeg-turbo-dev libpng-dev freetype-dev lcms2-dev libwebp-dev harfbuzz-dev fribidi-dev tcl-dev tk-dev python3-dev gcc

pip3 install --upgrade aligo
```

**Comment by Cyiming** [comment]
> 



> 你尝试下先在容器内执行这段代码看看，估计 Docker 里没有 Pillow 安装所需要的环境
> 
> ```
> apk add zlib libjpeg-turbo-dev libpng-dev freetype-dev lcms2-dev libwebp-dev harfbuzz-dev fribidi-dev tcl-dev tk-dev python3-dev 
> ```
> 
> 然后再安装依赖试试

进入容器是docker exec -it qinglong bash吗

我操作提示
ERROR: unable to select packages:
  bizCode (no such package):
    required by: world[bizCode]
  bizMsg (no such package):
    required by: world[bizMsg]
  lxml (no such package):
    required by: world[lxml]
root@qinglong:/ql $

**Comment by Ukenn2112** [comment]
> required by: world[bizCode]
> bizMsg (no such package):
> required by: world[bizMsg]
> lxml

试试这个？

`apk add --no-cache zlib libjpeg-turbo-dev libpng-dev freetype-dev lcms2-dev libwebp-dev harfbuzz-dev fribidi-dev tcl-dev tk-dev python3-dev gcc`

**Comment by Cyiming** [comment]
> > required by: world[bizCode]
> > bizMsg (no such package):
> > required by: world[bizMsg]
> > lxml
> 
> 试试这个？
> 
> `apk add --no-cache zlib libjpeg-turbo-dev libpng-dev freetype-dev lcms2-dev libwebp-dev harfbuzz-dev fribidi-dev tcl-dev tk-dev python3-dev gcc`

能跑通一点 后面还是报错

fetch https://mirrors.aliyun.com/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
fetch https://mirrors.aliyun.com/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:
  bizCode (no such package):
    required by: world[bizCode]
  bizMsg (no such package):
    required by: world[bizMsg]
  lxml (no such package):
    required by: world[lxml]
root@qinglong:/ql $

**Comment by Ukenn2112** [comment]
> > > required by: world[bizCode]
> > > bizMsg (no such package):
> > > required by: world[bizMsg]
> > > lxml
> > 
> > 
> > 试试这个？
> > `apk add --no-cache zlib libjpeg-turbo-dev libpng-dev freetype-dev lcms2-dev libwebp-dev harfbuzz-dev fribidi-dev tcl-dev tk-dev python3-dev gcc`
> 
> 能跑通一点 后面还是报错
> 
> fetch https://mirrors.aliyun.com/alpine/v3.15/main/x86_64/APKINDEX.tar.gz fetch https://mirrors.aliyun.com/alpine/v3.15/community/x86_64/APKINDEX.tar.gz ERROR: unable to select packages: bizCode (no such package): required by: world[bizCode] bizMsg (no such package): required by: world[bizMsg] lxml (no such package): required by: world[lxml] root@qinglong:/ql $

啊这给我整不会了试试这个
```
apk add --no-cache --virtual .build-deps gcc musl-dev python3-dev libffi libffi-dev openssl openssl-dev
pip3 install pip setuptools --upgrade
pip3 install cryptography~=3.2.1
pip3 install --upgrade aligo
```

**Comment by Cyiming** [comment]
> > > > required by: world[bizCode]
> > > > bizMsg (no such package):
> > > > required by: world[bizMsg]
> > > > lxml
> > > 
> > > 
> > > 试试这个？
> > > `apk add --no-cache zlib libjpeg-turbo-dev libpng-dev freetype-dev lcms2-dev libwebp-dev harfbuzz-dev fribidi-dev tcl-dev tk-dev python3-dev gcc`
> > 
> > 
> > 能跑通一点 后面还是报错
> > fetch https://mirrors.aliyun.com/alpine/v3.15/main/x86_64/APKINDEX.tar.gz fetch https://mirrors.aliyun.com/alpine/v3.15/community/x86_64/APKINDEX.tar.gz ERROR: unable to select packages: bizCode (no such package): required by: world[bizCode] bizMsg (no such package): required by: world[bizMsg] lxml (no such package): required by: world[lxml] root@qinglong:/ql $
> 
> 啊这给我整不会了试试这个
> 
> ```
> apk add --no-cache --virtual .build-deps gcc musl-dev python3-dev libffi libffi-dev openssl openssl-dev
> pip3 install pip setuptools --upgrade
> pip3 install cryptography~=3.2.1
> pip3 install --upgrade aligo
> ```

还是不行 报错太长了 截取几段在下面

大佬要不本地建个最新版本临时容器测试下？

```
 ERROR: unable to select packages:
  bizCode (no such package):
    required by: world[bizCode]
  bizMsg (no such package):
    required by: world[bizMsg]
  lxml (no such package):
    required by: world[lxml]

```
` Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [77 lines of output]`

`      error: subprocess-exited-with-error
      
        × Running setup.py install for cffi did not run successfully.
        │ exit code: 1
        ╰─> [47 lines of output]
      
                No working compiler found, or bogus compiler options passed to
                the compiler from Python's standard "distutils" module.  See
                the error messages above.  Likely, the problem is not related
                to CFFI but generic to the setup.py of any Python package that
                tries to compile C code.  (Hints: on OS/X 10.8, for errors about
                -mno-fused-madd see http://stackoverflow.com/questions/22313407/
                Otherwise, see https://wiki.python.org/moin/CompLangPython or
                the IRC channel #python on irc.libera.chat.)
      
                Trying to continue anyway.  If you are trying to install CFFI from
                a build done in a different context, you can ignore this warning.`

`  error: command 'gcc' failed: No such file or directory
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: legacy-install-failure
      
      × Encountered error while trying to install package.
      ╰─> cffi
      
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for output from the failure.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.`

`Running setup.py install for Pillow ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for Pillow did not run successfully.
  │ exit code: 1
  ╰─> [187 lines of output]`

`The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.
      
      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html`

`note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> Pillow

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.`

**Comment by Ukenn2112** [comment]
> > > > > required by: world[bizCode]
> > > > > bizMsg (no such package):
> > > > > required by: world[bizMsg]
> > > > > lxml
> > > > 
> > > > 
> > > > 试试这个？
> > > > `apk add --no-cache zlib libjpeg-turbo-dev libpng-dev freetype-dev lcms2-dev libwebp-dev harfbuzz-dev fribidi-dev tcl-dev tk-dev python3-dev gcc`
> > > 
> > > 
> > > 能跑通一点 后面还是报错
> > > fetch https://mirrors.aliyun.com/alpine/v3.15/main/x86_64/APKINDEX.tar.gz fetch https://mirrors.aliyun.com/alpine/v3.15/community/x86_64/APKINDEX.tar.gz ERROR: unable to select packages: bizCode (no such package): required by: world[bizCode] bizMsg (no such package): required by: world[bizMsg] lxml (no such package): required by: world[lxml] root@qinglong:/ql $
> > 
> > 
> > 啊这给我整不会了试试这个
> > ```
> > apk add --no-cache --virtual .build-deps gcc musl-dev python3-dev libffi libffi-dev openssl openssl-dev
> > pip3 install pip setuptools --upgrade
> > pip3 install cryptography~=3.2.1
> > pip3 install --upgrade aligo
> > ```
> 
> 还是不行 报错太长了 截取几段在下面
> 
> 大佬要不本地建个最新版本临时容器测试下？
> 
> `note: This error originates from a subprocess, and is likely not a problem with pip. error: legacy-install-failure
> 
> × Encountered error while trying to install package. ╰─> Pillow
> 
> note: This is an issue with the package mentioned above, not pip. hint: See above for output from the failure.`

这就很奇怪了，我今天下午使用qinglong `2.11.3` 和 `2.12.0` 用这个 https://github.com/Ukenn2112/qinglong_Backup/issues/2#issuecomment-1078716991
都可以正常安装，不知道为什么到了你这里就安装不上了，不好意思我实在是没法子了你要不上网上搜一下 `Pillow` 安装失败的相关的解决办法吧
